### ISSUE TITLE
Matrix channel?

### ISSUE THREAD

**Issue by Midou36O** [fosscord/fosscord#113]
I've been recently banned from discord for using a 3rd party client (as expected), and i wanted to continue to see the evolution of the project, maybe consider creating a matrix channel? (With bridging)

**Comment by ChrisChrome** [comment]
It turns out you were marked as a spammer
![image](https://user-images.githubusercontent.com/28414320/147511386-73dea615-1229-40fb-949f-b23c08e2bc0c.png)

**Comment by ChrisChrome** [comment]
@Midou36O If you have telegram hmu https://t.me/ChrisChrome

**Comment by Midou36O** [comment]
Closed because the main plan is to migrate to fosscord after it is deemed stable.

**Comment by TheArcaneBrony** [comment]
If there's anything preventing that at this point, it's the lack of a client I think. If you have the capacity to work on it, could you do so?

**Comment by ImAaronFR** [comment]
> If there's anything preventing that at this point, it's the lack of a client I think. If you have the capacity to work on it, could you do so?

well if it is why not migrate it already?

**Comment by TheArcaneBrony** [comment]
again, we need a client. I don't think we can use the discord.com client for anything officially outside a demo.

**Comment by Midou36O** [comment]
> If there's anything preventing that at this point, it's the lack of a client I think. If you have the capacity to work on it, could you do so?

By client you mean a client that has a different UI than discord to avoid copyright infringement?

**Comment by unknownPerson115** [comment]
> > If there's anything preventing that at this point, it's the lack of a client I think. If you have the capacity to work on it, could you do so?
> 
> By client you mean a client that has a different UI than discord to avoid copyright infringement?

thats exactly what i fear most

**Comment by Midou36O** [comment]
As long as there is nothing that looks like their branding and color on the default UI of the client, we could avoid that issue. (Altough this would reallly looks like a rip-off).

**Comment by erkinalp** [comment]
@FSG-Cat

**Comment by FSG-Cat** [comment]
Cat does have a unofficial fosscord related matrix room from back before the official guild adopted a stricter COC because Cat wanted to provide a place that has a more professional aura. 

The room has had its topic ammended to clarify that the problem that existed on the fosscord instance has been resolved. 

[#fosscord:feline.support](https://matrix.to/#/#fosscord:feline.support) A matrix.to link for the room and well also a copy of its alias. Not using the matrix URI because well Element has no support for it and it would be unfair to not use a scheme supported by element. 

Cat is ofc open to providing bridge services for the fosscord guild on discord.com to matrix.
