### ISSUE TITLE
Previewing guilds?

### ISSUE THREAD

**Issue by Karumtoo-Rexo** [fosscord/fosscord#170]
I noticed that the Discord dev team still didn't add [a user-friendly] way to preview guilds/servers before joining them.

Is it possible if _Fosscord_ would implement such a feature? Maybe an account dummy mode, if possible?

**Comment by Karumtoo-Rexo** [comment]
>_Issue/suggestion closed after 5 days due to no response or reaction._<

**Comment by n0bodysec** [comment]
Are u talking about the `PREVIEW_ENABLED` feature?

**Comment by Karumtoo-Rexo** [comment]
> Are u talking about the `PREVIEW_ENABLED` feature?

'Preview_Enabled' feature? Could you briefly explain what that feature is, please? It would help me to clarify what I would want for Fosscord.

{ Issue/Suggestion reopened. }

**Comment by n0bodysec** [comment]
Discord has a built-in system to preview guilds (only ones that are communities), this way you can "take a look" at the guild, but you can't send messages, add interactions, join voice channels, etc. (that's because you **are not** a member of the guild, you **do not** appear in the members list). You "leave"/stop seeing the server as soon as you click another guild, a DM channel, or if you close the Discord client.

If you check the official Discord API docs, you will see that guilds have something called "features".  
Features are, for the sake of redundancy, some extra features a guild has. For example, if a guild has the **VERIFIED** feature flag, then that guild will have the "verified badge" next to the server name.

Fosscord has te same features that Discord has, but with few additions.

Reference: https://discord.com/developers/docs/resources/guild#guild-object-guild-features

**Comment by Karumtoo-Rexo** [comment]
Ah, yes! That's what I'm referring to! Although, us users, could preview _all_ guilds (that's including those outside of [Discord-verified] communities).

Users have reported before that they'd like to preview all public, verified, and private guilds on Discord's support forums.
{Source [1](https://support.discord.com/hc/en-us/community/posts/360049491571-Previewing-servers) & [2](https://support.discord.com/hc/en-us/community/posts/360040721532-Server-Previews) for context.}

Or, as I posted before, a dummy account feature would be useful as an alternative.

**Comment by n0bodysec** [comment]
You *can* add the `PREVIEW_ENABLED` feature flag to *any* guild in Fosscord.

If you want a custom `preview` button next to a server invite or in another place, you need to wait the custom client to be finished, or you can edit the [test client](https://github.com/fosscord/fosscord-server/tree/master/api/client_test) in fosscord-server.

Dummy/shared accounts **are not recommended**.

**Comment by Karumtoo-Rexo** [comment]
> You can add the PREVIEW_ENABLED feature flag to any guild in Fosscord.
>
> If you want a custom preview button next to a server invite or in another place, you need to wait the custom client to be finished, or you can edit the [test client](https://github.com/fosscord/fosscord-server/tree/master/api/client_test) in fosscord-server.

Huh, that's a good idea. I'm gonna have to try that when the Test Client is fully online.

Oh, and...
> Dummy/shared accounts **are not recommended.**

I'll forget this part of the request, then. ((toothy grin))

Thank you for your answers, @n0bodysec. ((thumbs up))

{ Closed as resolved. }

**Comment by n0bodysec** [comment]
You are welcome!
